name: dukascango
description: DukaScanGO App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.32.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  form_field_validator: ^1.2.0
  android_intent_plus: ^5.0.2
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  intl: ^0.19.0
  polyline_do: ^1.0.0
  url_launcher: ^6.3.0
  socket_io_client: ^2.0.3
  firebase_messaging: ^15.0.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  flutter_local_notifications: ^17.1.2
  camera: ^0.10.5+9
  file_picker: ^5.0.0
  csv: ^5.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - Assets/
    - Assets/Logo/
    - Assets/svg/
    - assets/json/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

