// Mocks generated by Mockito 5.4.4 from annotations
// in dukascango/test/blocs/payments_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dukascango/domain/models/payment_gateway_model.dart' as _i3;
import 'package:dukascango/domain/models/wallet_ledger_entry_model.dart' as _i8;
import 'package:dukascango/domain/models/wallet_model.dart' as _i7;
import 'package:dukascango/domain/services/payment_gateway_interface.dart'
    as _i5;
import 'package:dukascango/domain/services/payment_gateway_manager.dart' as _i2;
import 'package:dukascango/domain/services/wallet_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PaymentGatewayManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentGatewayManager extends _i1.Mock
    implements _i2.PaymentGatewayManager {
  MockPaymentGatewayManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.PaymentGateway> get gateways => (super.noSuchMethod(
        Invocation.getter(#gateways),
        returnValue: <_i3.PaymentGateway>[],
      ) as List<_i3.PaymentGateway>);

  @override
  _i4.Future<void> loadGateways() => (super.noSuchMethod(
        Invocation.method(
          #loadGateways,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i5.PaymentGatewayInterface? getGatewayForCountry(String? countryCode) =>
      (super.noSuchMethod(Invocation.method(
        #getGatewayForCountry,
        [countryCode],
      )) as _i5.PaymentGatewayInterface?);

  @override
  _i5.PaymentGatewayInterface? getGatewayImplementation(
          _i3.PaymentGateway? gateway) =>
      (super.noSuchMethod(Invocation.method(
        #getGatewayImplementation,
        [gateway],
      )) as _i5.PaymentGatewayInterface?);
}

/// A class which mocks [WalletService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletService extends _i1.Mock implements _i6.WalletService {
  MockWalletService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createWalletForUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #createWalletForUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.Wallet?> getWallet(String? walletId) => (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [walletId],
        ),
        returnValue: _i4.Future<_i7.Wallet?>.value(),
      ) as _i4.Future<_i7.Wallet?>);

  @override
  _i4.Future<void> addLedgerEntry(
    String? walletId,
    _i8.WalletLedgerEntry? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLedgerEntry,
          [
            walletId,
            entry,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.WalletLedgerEntry>> getLedgerEntries(String? walletId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLedgerEntries,
          [walletId],
        ),
        returnValue: _i4.Future<List<_i8.WalletLedgerEntry>>.value(
            <_i8.WalletLedgerEntry>[]),
      ) as _i4.Future<List<_i8.WalletLedgerEntry>>);
}
